### ISSUE TITLE
Pie Chart Line (Inconsistent styling)

### ISSUE THREAD

**Issue by superduperkevin** [project-team-player/client#124]
**Describe the bug**
Google Chrome on different operating systems (Mac and Windows) has conflicting styles for the pie chart.

**To Reproduce**
1. Go to 'Games'
2. Click on 'any game'
3. See error on the pie chart

**Expected behavior**
Styling for the pie chart is intended to be consistent between various operating systems and browsers.

**Screenshots**
https://cdn.discordapp.com/attachments/618500096459407362/635880660858437632/image0.jpg

**Desktop (please complete the following information):**
 - OS: [Windows and iOS]
 - Browser [Chrome]
 - Version [Pre-alpha]

**Additional context**

**Comment by bjameson72** [comment]
This is fixed
